alias c='clip.exe'
alias cm='cd /home/steff007/mongodb/mongodb-linux-x86_64-3.6.5/bin'
alias dw='cd /mnt/c/users/jimst/Downloads'
alias g="grep"
alias ga='git add '
alias gb='git branch '
alias gc="git commit -a . -m "
alias gd='git diff'
alias gl='git log'
alias go='git checkout '
alias graph="git log --all --decorate --oneline --graph"
alias gs='git status '
alias h='history'
alias i3="ipython3"
alias la='ls -A'
alias ll='ls -alF'
alias lotto='curl --silent https://www.mnlottery.com/games/lotto | html2text | sed -e '1,72d' | v -'
alias lt='ls -lhrt'
alias md='mkdir'
alias mn='cd /mnt/c'
alias mp="cd /mnt/c/projects"
alias n='node'
alias nb='node --inspect-brk'
alias p3='python3'
alias p3='python3.6'
alias pc="pwd | clip.exe"
alias pow='powershell.exe'
alias s='history | grep '
alias v='vim '
alias vd='vim /mnt/c/all/d.txt'
alias vn="vim /mnt/c/all/n.txt"
alias y3='youtube-dl -x --audio-format mp3 '
alias y4='youtube-dl -f 18 '
